"""RT-DETRv4 inference + evaluation bridge for the external eval toolkit.

Writes the same three files ``main.py`` of the evaluation toolkit produces in a
dataset output folder (``<OUT_DIR>/<model_name>/<dataset>@<W>x<H>/``)::

    predictions.pkl               mmdet-style records (schema below)
    predictions_class_aware.json  COCO results list (pkl_to_coco + filter_predictions)
    results_cache_dual.pkl        {'version': 2, 'results': {'class_aware': ...,
                                   'class_agnostic': ...}, 'preds': [...]}

plus ``class_aware/`` and ``class_agnostic/bbox_metrics_and_errors.json``.
``main.py`` then finds the complete cache and does not run anything again.
Evaluation uses ``eval_toolkit/evaluation.py`` (a port of the toolkit's
``evaluation.py``) or, with ``--eval-toolkit DIR``, the toolkit's own module.
Plots and visualizations are left to the toolkit.

``predictions.pkl`` has one record per image, identical in schema to the
``run_inference()`` / TRT / ONNX paths of the toolkit::

    {
        'img_id':       int,                      # COCO image id from the GT json
        'img_path':     str,
        'ori_shape':    (orig_h, orig_w),
        'img_shape':    (input_h, input_w),       # network input size
        'scale_factor': (input_w / orig_w, input_h / orig_h),
        'pred_instances': {
            'bboxes':            (N, 4)  float32, xyxy, original-image pixels
            'scores':            (N,)    float32
            'labels':            (N,)    int64, index into the class order
            'keypoints':         (N, K, 2) float32, original-image pixels | None
            'keypoint_scores':   (N, K)  float32, sigmoid(visibility)     | None
            'keypoints_visible': (N, K)  float32, sigmoid(visibility)     | None
        },
    }

Images are iterated in the order of ``gt['images']`` (``--max-samples`` keeps
the first N), matching how the evaluation selects ``gt_img_ids``.
Preprocessing matches the validation pipeline of the vehicle configs:
PIL RGB -> Resize(H, W) (no keep-ratio) -> float in [0, 1].
"""

import argparse
import importlib
import json
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import torch
import torchvision.transforms.v2.functional as F
from PIL import Image, ImageFile

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

# NOTE: ``engine`` is imported lazily (load_yaml). Importing it runs
# faster_coco_eval.init_as_pycocotools(), which swaps the ``pycocotools``
# modules; the evaluation module must bind the real pycocotools first.

CACHE_VERSION = 2
EVAL_MODES = ('class_aware', 'class_agnostic')
AGNOSTIC_CAT_ID = 9999


def load_yaml(config_path):
    from engine.core import YAMLConfig
    return YAMLConfig(str(config_path))


ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.MAX_IMAGE_PIXELS = None

# Buffers that depend only on eval_spatial_size and are regenerated by the model.
SIZE_DEPENDENT_BUFFERS = ('anchors', 'valid_mask')
MAX_STRIDE = 32


def checkpoint_state(checkpoint):
    """Select EMA weights when available, accepting common checkpoint layouts."""
    if not isinstance(checkpoint, dict):
        raise TypeError('Checkpoint must contain a state-dict mapping')
    if 'ema' in checkpoint:
        ema = checkpoint['ema']
        return ema.get('module', ema) if isinstance(ema, dict) else ema
    if 'model' in checkpoint:
        return checkpoint['model']
    if 'state_dict' in checkpoint:
        return checkpoint['state_dict']
    return checkpoint


def load_model(config_path, checkpoint_path, device, input_size=None):
    """Build model + postprocessor; ``input_size`` is (H, W) or None for the YAML value."""
    cfg = load_yaml(config_path)
    if 'HGNetv2' in cfg.yaml_cfg:
        cfg.yaml_cfg['HGNetv2']['pretrained'] = False

    yaml_size = cfg.yaml_cfg.get('eval_spatial_size')
    if input_size is None:
        if not yaml_size:
            raise ValueError('Config has no eval_spatial_size; pass --input-width/--input-height')
        input_size = list(yaml_size)
    input_size = [int(input_size[0]), int(input_size[1])]
    if yaml_size and list(yaml_size) != input_size:
        print(f'eval_spatial_size override: {list(yaml_size)} -> {input_size} (H, W)')
    # Shared with HybridEncoder / DFINETransformer so anchors and positional
    # embeddings are built for the requested resolution.
    cfg.yaml_cfg['eval_spatial_size'] = input_size

    model = cfg.model
    state = checkpoint_state(torch.load(checkpoint_path, map_location='cpu', weights_only=False))
    state = {key.removeprefix('module.'): value for key, value in state.items()}

    model_state = model.state_dict()
    for key in list(state):
        if (key.rsplit('.', 1)[-1] in SIZE_DEPENDENT_BUFFERS and key in model_state
                and state[key].shape != model_state[key].shape):
            state[key] = model_state[key]
    missing, unexpected = model.load_state_dict(state, strict=False)
    if missing or unexpected:
        raise RuntimeError(f'Checkpoint mismatch: missing={missing[:20]} unexpected={unexpected[:20]}')

    # Cached decoder anchors use int(size / stride), but the backbone produces
    # ceil(size / stride) cells when the size is not a multiple of the largest
    # stride (e.g. 666). Build anchors from the real feature shapes instead.
    if any(size % MAX_STRIDE for size in input_size):
        print(f'Input {input_size} is not a multiple of {MAX_STRIDE}: '
              'using anchors generated from the actual feature-map shapes')
        for module in model.modules():
            if hasattr(module, '_generate_anchors') and hasattr(module, 'eval_spatial_size'):
                module.eval_spatial_size = None

    postprocessor = cfg.postprocessor
    return model.to(device).eval(), postprocessor.to(device).eval(), cfg, input_size


def resolve_dataset(cfg, gt_file=None, img_root=None):
    """Use explicit paths when given, else the YAML val_dataloader dataset."""
    dataset_cfg = cfg.yaml_cfg.get('val_dataloader', {}).get('dataset', {})
    gt_file = gt_file or dataset_cfg.get('ann_file')
    img_root = img_root or dataset_cfg.get('img_folder')
    if not gt_file or not img_root:
        raise ValueError('Pass --gt-file and --img-root (YAML val_dataloader has no '
                         'single ann_file/img_folder)')
    return gt_file, img_root


def build_label_map(model_classes, class_order):
    """Return an array mapping model label -> label in ``class_order`` (or None)."""
    if not class_order:
        return None
    if not model_classes:
        raise ValueError('--class-order needs class_names in the YAML config')
    missing = [name for name in model_classes if name not in class_order]
    if missing:
        raise ValueError(f'Classes {missing} from the config are absent in --class-order')
    return np.array([class_order.index(name) for name in model_classes], dtype=np.int64)


def preprocess(path, input_size):
    """Mirror the val transforms: Resize([H, W]) on PIL, then scale to [0, 1]."""
    with Image.open(path) as opened:
        image = opened.convert('RGB')
    width, height = image.size
    image = F.resize(image, input_size)
    tensor = F.to_dtype(F.to_image(image), torch.float32, scale=True)
    return tensor, (height, width)


def to_record(img_info, img_path, orig_hw, input_size, result, score_threshold,
              label_map=None):
    """Convert one postprocessor result to the evaluation pkl record."""
    scores = result['scores'].detach().float().cpu().numpy()
    keep = scores >= score_threshold

    labels = result['labels'].detach().cpu().numpy().astype(np.int64)[keep]
    if label_map is not None:
        labels = label_map[labels]

    keypoints = result.get('keypoints_xy')
    keypoint_scores = result.get('keypoint_scores')
    if keypoints is not None:
        keypoints = keypoints.detach().float().cpu().numpy()[keep].astype(np.float32)
        keypoint_scores = keypoint_scores.detach().float().cpu().numpy()[keep].astype(np.float32)

    orig_h, orig_w = orig_hw
    input_h, input_w = input_size
    return {
        'img_id': img_info['id'],
        'img_path': img_path,
        'ori_shape': (int(orig_h), int(orig_w)),
        'img_shape': (int(input_h), int(input_w)),
        'scale_factor': (input_w / orig_w, input_h / orig_h),
        'pred_instances': {
            'bboxes': result['boxes'].detach().float().cpu().numpy()[keep].astype(np.float32),
            'scores': scores[keep].astype(np.float32),
            'labels': labels,
            'keypoints': keypoints,
            'keypoint_scores': keypoint_scores,
            'keypoints_visible': None if keypoint_scores is None else keypoint_scores.copy(),
        },
    }



# ── Inference ─────────────────────────────────────────────────────────────────

@torch.inference_mode()
def predict(args):
    """Run inference; return (records, class names by record label, gt_file)."""
    device = torch.device(args.device)
    input_size = None
    if args.input_width is not None or args.input_height is not None:
        if args.input_width is None or args.input_height is None:
            raise ValueError('Pass both --input-width and --input-height')
        input_size = [args.input_height, args.input_width]

    model, postprocessor, cfg, input_size = load_model(
        args.config, args.checkpoint, device, input_size)
    model_classes = cfg.yaml_cfg.get('class_names')
    label_map = build_label_map(model_classes, args.class_order)
    gt_file, img_root = resolve_dataset(cfg, args.gt_file, args.img_root)

    with open(gt_file) as f:
        images = json.load(f)['images']
    if args.max_samples is not None:
        images = images[:args.max_samples]

    print(f'Config      : {args.config}')
    print(f'Checkpoint  : {args.checkpoint}')
    print(f'GT file     : {gt_file}')
    print(f'Image root  : {img_root}')
    print(f'Images      : {len(images)}')
    print(f'Input (H,W) : {tuple(input_size)}')
    print(f'Classes     : {model_classes}' +
          (f' -> {args.class_order}' if label_map is not None else ''))

    predictions, skipped = [], 0
    batch = []

    def flush():
        tensors = torch.stack([item[2] for item in batch]).to(device)
        orig_sizes = torch.tensor([[w, h] for _, _, _, (h, w) in batch],
                                  dtype=torch.float32, device=device)
        with torch.autocast(device_type=device.type, dtype=torch.float16,
                            enabled=args.fp16 and device.type == 'cuda'):
            outputs = model(tensors)
        outputs = {k: v.float() if torch.is_tensor(v) else v for k, v in outputs.items()}
        results = postprocessor(outputs, orig_sizes)
        for (img_info, img_path, _, orig_hw), result in zip(batch, results):
            predictions.append(to_record(img_info, img_path, orig_hw, input_size, result,
                                         args.score_threshold, label_map))
        batch.clear()

    for index, img_info in enumerate(images, start=1):
        img_path = os.path.join(img_root, img_info['file_name'])
        if not os.path.exists(img_path):
            skipped += 1
            continue
        tensor, orig_hw = preprocess(img_path, input_size)
        batch.append((img_info, img_path, tensor, orig_hw))
        if len(batch) >= args.batch_size:
            flush()
        if index % 100 == 0 or index == len(images):
            print(f'  {index}/{len(images)}', flush=True)
    if batch:
        flush()

    if skipped:
        print(f'Warning: {skipped} images not found on disk')
    label_names = list(args.class_order) if label_map is not None else model_classes
    return predictions, label_names, gt_file


# ── pkl -> class-aware COCO list (toolkit: pkl_to_coco + filter_predictions) ──

def records_to_coco(records, label_names, cat_name_to_id, score_threshold, gt_img_ids):
    """Flatten pkl records into a class-aware COCO results list.

    Labels are mapped to GT category ids by class name. Keypoints are flat
    ``[x, y, v, ...]`` with ``v = sigmoid(visibility)``, as the toolkit expects.
    """
    coco, unmapped = [], {}
    for record in records:
        if record['img_id'] not in gt_img_ids:
            continue
        instances = record['pred_instances']
        keypoints = instances.get('keypoints')
        visible = instances.get('keypoints_visible')
        keypoint_scores = instances.get('keypoint_scores')
        for index, score in enumerate(instances['scores']):
            score = float(score)
            if score < score_threshold:
                continue
            name = label_names[int(instances['labels'][index])]
            if name not in cat_name_to_id:
                unmapped[name] = unmapped.get(name, 0) + 1
                continue
            x1, y1, x2, y2 = (float(v) for v in instances['bboxes'][index])
            prediction = {
                'image_id': record['img_id'],
                'category_id': cat_name_to_id[name],
                'bbox': [x1, y1, x2 - x1, y2 - y1],
                'score': score,
                'img_path': record['img_path'],
            }
            if keypoints is not None:
                prediction['keypoints'] = [
                    float(value)
                    for (x, y), v in zip(keypoints[index], visible[index])
                    for value in (x, y, v)
                ]
                prediction['keypoint_scores'] = [float(v) for v in keypoint_scores[index]]
            coco.append(prediction)
    if unmapped:
        print(f'Warning: dropped detections of classes absent from the GT file: {unmapped}')
    return coco


# ── Dual evaluation (toolkit main.py: _evaluate_and_cache, without plots) ─────

def load_eval_module(toolkit_dir, max_dets, kpt_names):
    """Import the toolkit's evaluation.py (``toolkit_dir``) or the bundled port."""
    if toolkit_dir:
        sys.path.insert(0, str(Path(toolkit_dir).resolve()))
        module = importlib.import_module('evaluation')
    else:
        module = importlib.import_module('eval_toolkit.evaluation')
        module.MAX_DETS = max_dets
        module.KPT_NAMES = kpt_names
    if not module.COCOeval.__module__.startswith('pycocotools'):
        print(f'Warning: evaluation uses {module.COCOeval.__module__}.COCOeval, '
              'not pycocotools; install pycocotools for identical metrics')
    print(f'Evaluation  : {module.__file__} (MAX_DETS={module.MAX_DETS})')
    return module


def evaluate_and_cache(eval_utils, preds, coco_gt, vehicle_cat_ids, ds_cat_id_to_name,
                       args, out_dir, cache_path):
    """Evaluate the class-aware ``preds`` in both modes and save the dual cache."""
    ag_preds, ag_gt = eval_utils.make_class_agnostic(
        preds, coco_gt, group_ids=vehicle_cat_ids)

    mode_data = {
        'class_aware': (preds, coco_gt, vehicle_cat_ids, ds_cat_id_to_name),
        'class_agnostic': (ag_preds, ag_gt, [AGNOSTIC_CAT_ID], {AGNOSTIC_CAT_ID: 'vehicle'}),
    }

    results = {}
    for mode, (mode_preds, mode_gt, cat_ids, cat_id_to_name) in mode_data.items():
        mode_out = os.path.join(out_dir, mode)
        os.makedirs(mode_out, exist_ok=True)
        print(f'\n{"=" * 25} {mode.upper()} {"=" * 25}')

        res = eval_utils.evaluate_bbox(mode_preds, cat_ids, mode_gt, extended_sizes=True)
        res['error_stats'] = eval_utils.evaluate_bbox_errors(mode_preds, cat_ids, mode_gt)
        res['occlusion_stats'] = eval_utils.evaluate_bbox_by_occlusion(
            mode_preds, cat_ids, mode_gt)
        res['kpt_names'] = args.kpt_names

        evaluate_keypoints_for_mode(eval_utils, res, mode_preds, mode_gt, cat_ids, args)
        save_bbox_metrics_json(res, mode_out)
        print_summary(res, mode, cat_id_to_name)
        results[mode] = res

    with open(cache_path, 'wb') as f:
        pickle.dump({'version': CACHE_VERSION, 'results': results, 'preds': preds}, f)
    print(f'Dual cache saved → {cache_path}')
    return results


def evaluate_keypoints_for_mode(eval_utils, results, preds, coco_gt, cat_ids, args):
    gt_has_keypoints = any(
        a.get('num_keypoints', 0) > 0
        for a in coco_gt.loadAnns(coco_gt.getAnnIds()))

    if not any('keypoints' in p for p in preds):
        print('── No keypoints in predictions — skipping KP eval ──')
        return
    if not gt_has_keypoints:
        print('── No GT keypoint annotations — skipping KP eval ──')
        return

    print('\n── Keypoint evaluation ───────────────────────────────')
    kp_results = eval_utils.evaluate_keypoints(
        preds=preds,
        coco_gt=coco_gt,
        cat_ids=cat_ids,
        thresholds=[5.0, 10.0],
        vis_thr=0.5,
        conf_thrs=args.kp_conf_thrs,
        model_type=args.model_type,
        margin=0.05,
        crop_size=512,
        kpt_names=args.kpt_names,
    )
    results['kp'] = {
        k: v for k, v in kp_results.items()
        if k not in ('coco_eval', 'coco_dt')
    }


def save_bbox_metrics_json(results, out_dir):
    payload = {
        key: results.get(key)
        for key in ('stats', 'per_cat', 'size_stats', 'per_cat_size_stats',
                    'error_stats', 'occlusion_stats')
    }
    path = os.path.join(out_dir, 'bbox_metrics_and_errors.json')
    with open(path, 'w') as f:
        json.dump(_jsonable(payload), f, indent=2)
    print(f'Metrics JSON saved → {path}')


def _jsonable(obj):
    if isinstance(obj, dict):
        return {str(k): _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(v) for v in obj]
    if hasattr(obj, 'tolist'):
        return obj.tolist()
    if isinstance(obj, (int, float, str, bool)) or obj is None:
        return obj
    return str(obj)


def print_summary(results, mode, cat_id_to_name=None):
    s = results['stats']
    print(f'\n── {mode} summary ──')
    print(f'AP@0.50:0.95={s[0]:.3f}  AP@0.50={s[1]:.3f}  AP@0.75={s[2]:.3f}')
    if results.get('size_stats'):
        print('Custom sizes: ' + '  '.join(
            f'{name}={results["size_stats"][name]["ap"]:.3f}'
            for name in ['small', 'medium', 'large', 'xlarge', 'xxlarge']
            if name in results['size_stats']))
    print(f'AR@1={s[6]:.3f}  AR@10={s[7]:.3f}  AR@MAX={s[8]:.3f}')
    err = results.get('error_stats', {}).get('iou', {})
    for thr in ('0.50', '0.75'):
        if thr not in err:
            continue
        d = err[thr]['all']
        print(f'IoU={thr}: TP={d["tp"]} FP={d["fp"]} FN={d["fn"]}  '
              f'P={d["precision"]:.3f} R={d["recall"]:.3f} F1={d["f1"]:.3f}')
    if cat_id_to_name and len(results.get('per_cat', {})) > 1:
        print('Per category:')
        for cat_id, stats in results['per_cat'].items():
            print(f'  {cat_id_to_name.get(cat_id, str(cat_id)):12s}  '
                  f'AP={stats[0]:.3f} AP50={stats[1]:.3f} '
                  f'AP75={stats[2]:.3f} AR={stats[8]:.3f}')


# ── Entry point ───────────────────────────────────────────────────────────────

def resolve_out_dir(args):
    """Explicit --out-dir, or <out-root>/<model-name>/<dataset-name>@<W>x<H> like main.py."""
    if args.out_dir:
        return Path(args.out_dir)
    if args.out_root and args.model_name and args.dataset_name:
        scale = (f'{args.input_width}x{args.input_height}'
                 if args.input_width and args.input_height else 'default')
        return Path(args.out_root) / args.model_name / f'{args.dataset_name}@{scale}'
    if args.output:
        return Path(args.output).parent
    raise ValueError('Pass --out-dir, or --out-root + --model-name + --dataset-name')


def run(args):
    out_dir = resolve_out_dir(args)
    out_dir.mkdir(parents=True, exist_ok=True)
    pkl_path = Path(args.output) if args.output else out_dir / 'predictions.pkl'
    json_path = out_dir / 'predictions_class_aware.json'
    cache_path = out_dir / 'results_cache_dual.pkl'
    if not args.config:
        raise ValueError('--config is required')

    # Must happen before anything imports ``engine`` (see note at the top).
    eval_utils = None if args.no_eval else load_eval_module(
        args.eval_toolkit, args.max_dets, args.kpt_names)
    COCO = eval_utils.COCO if eval_utils else None

    # ── 1. predictions.pkl ──
    if pkl_path.exists() and not args.force:
        print(f'Reusing predictions → {pkl_path} (pass --force to rerun inference)')
        with open(pkl_path, 'rb') as f:
            records = pickle.load(f)
        cfg = load_yaml(args.config)
        label_names = list(args.class_order or cfg.yaml_cfg.get('class_names') or [])
        gt_file, _ = resolve_dataset(cfg, args.gt_file, args.img_root or '-')
    else:
        if not args.checkpoint:
            raise ValueError('--checkpoint is required to run inference')
        records, label_names, gt_file = predict(args)
        with open(pkl_path, 'wb') as f:
            pickle.dump(records, f)
        num_dets = sum(len(p['pred_instances']['scores']) for p in records)
        print(f'Saved {len(records)} RT-DETRv4 predictions ({num_dets} detections) → {pkl_path}')
    if not label_names:
        raise ValueError('No class names: add class_names to the YAML or pass --class-order')

    # ── 2. predictions_class_aware.json ──
    with open(gt_file) as f:
        gt_data = json.load(f)
    ds_cat_name_to_id = {c['name']: c['id'] for c in gt_data['categories']}
    ds_cat_id_to_name = {c['id']: c['name'] for c in gt_data['categories']}
    gt_img_ids = {img['id'] for img in gt_data['images'][:args.max_samples]}

    preds = records_to_coco(records, label_names, ds_cat_name_to_id,
                            args.score_threshold, gt_img_ids)
    with open(json_path, 'w') as f:
        json.dump(preds, f, indent=2)
    print(f'Predictions saved → {json_path} ({len(preds)} detections)')

    # ── 3. results_cache_dual.pkl ──
    if eval_utils is None:
        return str(pkl_path)
    vehicle_cat_ids = [ds_cat_name_to_id[n] for n in label_names if n in ds_cat_name_to_id]
    coco_gt = COCO(gt_file)
    evaluate_and_cache(eval_utils, preds, coco_gt, vehicle_cat_ids, ds_cat_id_to_name,
                       args, str(out_dir), str(cache_path))
    return str(pkl_path)


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    model = parser.add_argument_group('model / inference')
    model.add_argument('-c', '--config', required=True)
    model.add_argument('-r', '--checkpoint', help='Required unless predictions.pkl is reused')
    model.add_argument('-d', '--device', default='cuda:0' if torch.cuda.is_available() else 'cpu')
    model.add_argument('-b', '--batch-size', type=int, default=1)
    model.add_argument('--score-threshold', type=float, default=0.0,
                       help='Use the same value as ModelConfig.score_thr')
    model.add_argument('--input-width', type=int,
                       help='Network input width (default: YAML eval_spatial_size)')
    model.add_argument('--input-height', type=int,
                       help='Network input height (default: YAML eval_spatial_size)')
    model.add_argument('--class-order', nargs='+',
                       help='Class names in the evaluation label order (MODEL_CLASSES); '
                            'pkl labels are remapped by name. Default: YAML class_names')
    model.add_argument('--fp16', action='store_true')
    model.add_argument('--force', action='store_true',
                       help='Rerun inference even if predictions.pkl exists')

    data = parser.add_argument_group('dataset')
    data.add_argument('--gt-file', help='COCO GT json (default: YAML val ann_file)')
    data.add_argument('--img-root', help='Image folder (default: YAML val img_folder)')
    data.add_argument('--max-samples', type=int)

    out = parser.add_argument_group('outputs')
    out.add_argument('--out-dir', help='Dataset output folder for the three files')
    out.add_argument('--out-root', help='OUT_DIR of the toolkit (with --model-name/--dataset-name)')
    out.add_argument('--model-name', help='ModelConfig.name')
    out.add_argument('--dataset-name', help='DatasetConfig.name')
    out.add_argument('-o', '--output', help='predictions pkl path (default: <out-dir>/predictions.pkl)')

    ev = parser.add_argument_group('evaluation')
    ev.add_argument('--no-eval', action='store_true',
                    help='Only write predictions.pkl and predictions_class_aware.json')
    ev.add_argument('--eval-toolkit',
                    help="Folder with the toolkit's evaluation.py/config.py to use instead of "
                         'the bundled port')
    ev.add_argument('--max-dets', type=int, default=100, help='config.MAX_DETS of the toolkit')
    ev.add_argument('--kp-conf-thrs', type=float, nargs='+', default=[0.0],
                    help='ModelConfig.kp_conf_thrs')
    ev.add_argument('--kpt-names', nargs='+', help='DatasetConfig.kpt_names')
    ev.add_argument('--model-type', default='rtdetrv4_external', help='ModelConfig.model_type')
    return parser


def parse_args(argv=None):
    return build_parser().parse_args(argv)


if __name__ == '__main__':
    run(parse_args())
