"""Export RT-DETRv4 predictions in the mmdet-style ``predictions.pkl`` layout.

The output is a pickled list with one record per image, identical in schema
to the ``run_inference()`` / TRT / ONNX paths of the external evaluation
toolkit, so ``pkl_to_coco()`` and the evaluation scripts can consume it
unchanged::

    {
        'img_id':       int,                      # COCO image id from the GT json
        'img_path':     str,
        'ori_shape':    (orig_h, orig_w),
        'img_shape':    (input_h, input_w),       # network input size
        'scale_factor': (input_w / orig_w, input_h / orig_h),
        'pred_instances': {
            'bboxes':            (N, 4)  float32, xyxy, original-image pixels
            'scores':            (N,)    float32
            'labels':            (N,)    int64, index into the class order
            'keypoints':         (N, K, 2) float32, original-image pixels | None
            'keypoint_scores':   (N, K)  float32, sigmoid(visibility)     | None
            'keypoints_visible': (N, K)  float32, sigmoid(visibility)     | None
        },
    }

Images are iterated in the order of ``gt['images']`` (``--max-samples`` keeps
the first N), matching how the evaluation selects ``gt_img_ids``.
Preprocessing matches the validation pipeline of the vehicle configs:
PIL RGB -> Resize(H, W) (no keep-ratio) -> float in [0, 1].
"""

import argparse
import json
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import torch
import torchvision.transforms.v2.functional as F
from PIL import Image, ImageFile

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from engine.core import YAMLConfig


ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.MAX_IMAGE_PIXELS = None

# Buffers that depend only on eval_spatial_size and are regenerated by the model.
SIZE_DEPENDENT_BUFFERS = ('anchors', 'valid_mask')
MAX_STRIDE = 32


def checkpoint_state(checkpoint):
    """Select EMA weights when available, accepting common checkpoint layouts."""
    if not isinstance(checkpoint, dict):
        raise TypeError('Checkpoint must contain a state-dict mapping')
    if 'ema' in checkpoint:
        ema = checkpoint['ema']
        return ema.get('module', ema) if isinstance(ema, dict) else ema
    if 'model' in checkpoint:
        return checkpoint['model']
    if 'state_dict' in checkpoint:
        return checkpoint['state_dict']
    return checkpoint


def load_model(config_path, checkpoint_path, device, input_size=None):
    """Build model + postprocessor; ``input_size`` is (H, W) or None for the YAML value."""
    cfg = YAMLConfig(str(config_path))
    if 'HGNetv2' in cfg.yaml_cfg:
        cfg.yaml_cfg['HGNetv2']['pretrained'] = False

    yaml_size = cfg.yaml_cfg.get('eval_spatial_size')
    if input_size is None:
        if not yaml_size:
            raise ValueError('Config has no eval_spatial_size; pass --input-width/--input-height')
        input_size = list(yaml_size)
    input_size = [int(input_size[0]), int(input_size[1])]
    if yaml_size and list(yaml_size) != input_size:
        print(f'eval_spatial_size override: {list(yaml_size)} -> {input_size} (H, W)')
    # Shared with HybridEncoder / DFINETransformer so anchors and positional
    # embeddings are built for the requested resolution.
    cfg.yaml_cfg['eval_spatial_size'] = input_size

    model = cfg.model
    state = checkpoint_state(torch.load(checkpoint_path, map_location='cpu', weights_only=False))
    state = {key.removeprefix('module.'): value for key, value in state.items()}

    model_state = model.state_dict()
    for key in list(state):
        if (key.rsplit('.', 1)[-1] in SIZE_DEPENDENT_BUFFERS and key in model_state
                and state[key].shape != model_state[key].shape):
            state[key] = model_state[key]
    missing, unexpected = model.load_state_dict(state, strict=False)
    if missing or unexpected:
        raise RuntimeError(f'Checkpoint mismatch: missing={missing[:20]} unexpected={unexpected[:20]}')

    # Cached decoder anchors use int(size / stride), but the backbone produces
    # ceil(size / stride) cells when the size is not a multiple of the largest
    # stride (e.g. 666). Build anchors from the real feature shapes instead.
    if any(size % MAX_STRIDE for size in input_size):
        print(f'Input {input_size} is not a multiple of {MAX_STRIDE}: '
              'using anchors generated from the actual feature-map shapes')
        for module in model.modules():
            if hasattr(module, '_generate_anchors') and hasattr(module, 'eval_spatial_size'):
                module.eval_spatial_size = None

    postprocessor = cfg.postprocessor
    return model.to(device).eval(), postprocessor.to(device).eval(), cfg, input_size


def resolve_dataset(cfg, gt_file=None, img_root=None):
    """Use explicit paths when given, else the YAML val_dataloader dataset."""
    dataset_cfg = cfg.yaml_cfg.get('val_dataloader', {}).get('dataset', {})
    gt_file = gt_file or dataset_cfg.get('ann_file')
    img_root = img_root or dataset_cfg.get('img_folder')
    if not gt_file or not img_root:
        raise ValueError('Pass --gt-file and --img-root (YAML val_dataloader has no '
                         'single ann_file/img_folder)')
    return gt_file, img_root


def build_label_map(model_classes, class_order):
    """Return an array mapping model label -> label in ``class_order`` (or None)."""
    if not class_order:
        return None
    if not model_classes:
        raise ValueError('--class-order needs class_names in the YAML config')
    missing = [name for name in model_classes if name not in class_order]
    if missing:
        raise ValueError(f'Classes {missing} from the config are absent in --class-order')
    return np.array([class_order.index(name) for name in model_classes], dtype=np.int64)


def preprocess(path, input_size):
    """Mirror the val transforms: Resize([H, W]) on PIL, then scale to [0, 1]."""
    with Image.open(path) as opened:
        image = opened.convert('RGB')
    width, height = image.size
    image = F.resize(image, input_size)
    tensor = F.to_dtype(F.to_image(image), torch.float32, scale=True)
    return tensor, (height, width)


def to_record(img_info, img_path, orig_hw, input_size, result, score_threshold,
              label_map=None):
    """Convert one postprocessor result to the evaluation pkl record."""
    scores = result['scores'].detach().float().cpu().numpy()
    keep = scores >= score_threshold

    labels = result['labels'].detach().cpu().numpy().astype(np.int64)[keep]
    if label_map is not None:
        labels = label_map[labels]

    keypoints = result.get('keypoints_xy')
    keypoint_scores = result.get('keypoint_scores')
    if keypoints is not None:
        keypoints = keypoints.detach().float().cpu().numpy()[keep].astype(np.float32)
        keypoint_scores = keypoint_scores.detach().float().cpu().numpy()[keep].astype(np.float32)

    orig_h, orig_w = orig_hw
    input_h, input_w = input_size
    return {
        'img_id': img_info['id'],
        'img_path': img_path,
        'ori_shape': (int(orig_h), int(orig_w)),
        'img_shape': (int(input_h), int(input_w)),
        'scale_factor': (input_w / orig_w, input_h / orig_h),
        'pred_instances': {
            'bboxes': result['boxes'].detach().float().cpu().numpy()[keep].astype(np.float32),
            'scores': scores[keep].astype(np.float32),
            'labels': labels,
            'keypoints': keypoints,
            'keypoint_scores': keypoint_scores,
            'keypoints_visible': None if keypoint_scores is None else keypoint_scores.copy(),
        },
    }


@torch.inference_mode()
def run(args):
    device = torch.device(args.device)
    input_size = None
    if args.input_width is not None or args.input_height is not None:
        if args.input_width is None or args.input_height is None:
            raise ValueError('Pass both --input-width and --input-height')
        input_size = [args.input_height, args.input_width]

    model, postprocessor, cfg, input_size = load_model(
        args.config, args.checkpoint, device, input_size)
    model_classes = cfg.yaml_cfg.get('class_names')
    label_map = build_label_map(model_classes, args.class_order)
    gt_file, img_root = resolve_dataset(cfg, args.gt_file, args.img_root)

    with open(gt_file) as f:
        images = json.load(f)['images']
    if args.max_samples is not None:
        images = images[:args.max_samples]

    print(f'Config      : {args.config}')
    print(f'Checkpoint  : {args.checkpoint}')
    print(f'GT file     : {gt_file}')
    print(f'Image root  : {img_root}')
    print(f'Images      : {len(images)}')
    print(f'Input (H,W) : {tuple(input_size)}')
    print(f'Classes     : {model_classes}' +
          (f' -> {args.class_order}' if label_map is not None else ''))

    predictions, skipped = [], 0
    batch = []

    def flush():
        tensors = torch.stack([item[2] for item in batch]).to(device)
        orig_sizes = torch.tensor([[w, h] for _, _, _, (h, w) in batch],
                                  dtype=torch.float32, device=device)
        with torch.autocast(device_type=device.type, dtype=torch.float16,
                            enabled=args.fp16 and device.type == 'cuda'):
            outputs = model(tensors)
        outputs = {k: v.float() if torch.is_tensor(v) else v for k, v in outputs.items()}
        results = postprocessor(outputs, orig_sizes)
        for (img_info, img_path, _, orig_hw), result in zip(batch, results):
            predictions.append(to_record(img_info, img_path, orig_hw, input_size, result,
                                         args.score_threshold, label_map))
        batch.clear()

    for index, img_info in enumerate(images, start=1):
        img_path = os.path.join(img_root, img_info['file_name'])
        if not os.path.exists(img_path):
            skipped += 1
            continue
        tensor, orig_hw = preprocess(img_path, input_size)
        batch.append((img_info, img_path, tensor, orig_hw))
        if len(batch) >= args.batch_size:
            flush()
        if index % 100 == 0 or index == len(images):
            print(f'  {index}/{len(images)}', flush=True)
    if batch:
        flush()

    if skipped:
        print(f'Warning: {skipped} images not found on disk')

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'wb') as f:
        pickle.dump(predictions, f)
    num_dets = sum(len(p['pred_instances']['scores']) for p in predictions)
    print(f'Saved {len(predictions)} RT-DETRv4 predictions ({num_dets} detections) -> {output}')
    return str(output)


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-c', '--config', required=True)
    parser.add_argument('-r', '--checkpoint', required=True)
    parser.add_argument('-o', '--output', required=True, help='Output .pkl path')
    parser.add_argument('-d', '--device', default='cuda:0' if torch.cuda.is_available() else 'cpu')
    parser.add_argument('-b', '--batch-size', type=int, default=1)
    parser.add_argument('--score-threshold', type=float, default=0.0)
    parser.add_argument('--input-width', type=int,
                        help='Network input width (default: YAML eval_spatial_size)')
    parser.add_argument('--input-height', type=int,
                        help='Network input height (default: YAML eval_spatial_size)')
    parser.add_argument('--gt-file', help='COCO GT json (default: YAML val ann_file)')
    parser.add_argument('--img-root', help='Image folder (default: YAML val img_folder)')
    parser.add_argument('--max-samples', type=int)
    parser.add_argument('--class-order', nargs='+',
                        help='Class names in the evaluation label order (e.g. MODEL_CLASSES); '
                             'model labels are remapped by name. Default: YAML class_names order')
    parser.add_argument('--fp16', action='store_true')
    return parser.parse_args(argv)


if __name__ == '__main__':
    run(parse_args())
